// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr71OIkoe3JwgXV0-gRwiNgMKfkeX4JSs',
    appId: '1:733426712607:web:ffd576ffb2f0a1c41a152a',
    messagingSenderId: '733426712607',
    projectId: 'social-media-app-58679',
    authDomain: 'social-media-app-58679.firebaseapp.com',
    storageBucket: 'social-media-app-58679.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrc6Yl1011rCrfBdaVUgfb4b9qLSV6os',
    appId: '1:733426712607:android:685f8084c35baa931a152a',
    messagingSenderId: '733426712607',
    projectId: 'social-media-app-58679',
    storageBucket: 'social-media-app-58679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvkpFiIeIHfgQTLPVws23u62HaoY1No4',
    appId: '1:733426712607:ios:f3b1a196b2c2a8c51a152a',
    messagingSenderId: '733426712607',
    projectId: 'social-media-app-58679',
    storageBucket: 'social-media-app-58679.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
